spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/in42?serverTimezone=Asia/Seoul
    username: root
    password: "!Qweasd200517"

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false
    open-in-view: false

  security:
    oauth2.client:
      authenticationScheme: header
      registration:
        42:
          client-id: "u-s4t2ud-d844cacf547981dc5517aa08e06fe4219cc13de1946aa919bcaa6ed4fa260fc5"
          client-secret: "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"
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" #"http://localhost:8080/test"
          authorization-grant-type: authorization_code
          scope: public
      provider:
        42:
          authorization-uri: "https://api.intra.42.fr/oauth/authorize"
          token-uri: "https://api.intra.42.fr/oauth/token"
          user-info-uri: "https://api.intra.42.fr/v2/me"
          user-name-attribute: id

# cors ??
cors:
  allowed-origins: 'http://localhost:8080,http://localhost:3000,http://10.18.238.114:3000,http://10.18.238.114:8080'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: '*'
  allowed-Credentials: true
  max-age: 3600

jwt:
  secret: fske256d3433kf2@er454ddd!35435rd!!!dkzfefdsdfjldkjf!dxfd5dsfx2432dszdfdsfsfs12xdfds2sa

info:
  web:
    frontUrl: 'http://localhost:8080'
